[package]
name = "litebox_desktop_host"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
windows-sys = { version = "0.60.2", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Media_Audio",
    "Win32_System_Threading",
    "Win32_System_LibraryLoader",
    "Win32_System_Console",
    "Win32_UI_Shell",
] }

[profile.release]
debug = 0
incremental = false
opt-level = 2
lto = "thin"
strip = true

[profile.dev]
debug = 0
incremental = false
